version: '3.4'

services:
  ms_users_auth:
    image: ${DOCKER_REGISTRY-}msusersauth
    environment:
        - CadenaSQL=Server=192.168.0.17,1433; Database=AuthServiceDB; User ID=Nodens; Password=yourStrong(!)Password;
        - CadenaMongo=mongodb://Nodens:secret@192.168.0.17:27018/
    build:
      context: .
      dockerfile: MS_Users_Auth/Dockerfile
